---
title: "Instacart Flexdashboard"
output:
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
    theme: cerulean
---

```{r}
suppressPackageStartupMessages({
library(tidyverse)
library(plotly)
library(p8105.datasets)
library(lubridate)
})

data("instacart", package = "p8105.datasets")

dow_labs <- c("Sun","Mon","Tue","Wed","Thu","Fri","Sat")
insta <- instacart |>
mutate(
order_dow = factor(order_dow, levels = 0:6, labels = dow_labs),
reordered = factor(reordered, levels = c(0, 1), labels = c("No", "Yes"))
)

```

Row
-------------------------------------

### Top 15 Aisles (Bar Plot)

```{r}
# Plot for Top 15 Aisles (Bar Plot)
top_aisles <- insta |>
  count(aisle, sort = TRUE) |>
  slice_head(n = 15) |>
  mutate(aisle = fct_reorder(aisle, n))  # reorder factor by n

plot_ly(top_aisles,
        x = ~n, y = ~aisle,
        type = "bar", orientation = "h") |>
  layout(
    title = "Top 15 Aisles by Product Count",
    xaxis = list(title = "Number of Products"),
    yaxis = list(title = "Aisle", categoryorder = "total ascending")  # largest at top
  )
```

Row
-------------------------------------

### Plot for Orders by Hour and Day (Line Plot)

```{r}
# Plot for Orders by Hour and Day (Line Plot)
hour_by_dow <- insta |>
  count(order_dow, order_hour_of_day)

plot_ly(hour_by_dow,
        x = ~order_hour_of_day, y = ~n,
        color = ~order_dow, type = "scatter", mode = "lines+markers") |>
  layout(title = "Orders by Hour of Day and Day of Week",
         xaxis = list(title = "Hour (0–23)"),
         yaxis = list(title = "Number of Orders"))
```

Row
-------------------------------------

### Plot for Add-to-Cart Order by Department (Box Plot)

```{r}
# Plot for Add-to-Cart Order by Department (Box Plot)
dept_box <- insta |>
  filter(add_to_cart_order <= 50) |>
  group_by(department) |>
  filter(n() > 2000) |>
  ungroup()

plot_ly(dept_box,
        x = ~department, y = ~add_to_cart_order,
        type = "box") |>
  layout(title = "Add-to-Cart Order by Department",
         xaxis = list(title = "Department", tickangle = 45),
         yaxis = list(title = "Add-to-Cart Position (≤ 50)"))
```





